### ISSUE TITLE
長時間74式を起動している状態で艦船図鑑/装備図鑑を開くと74式がフリーズする

### ISSUE THREAD

**Issue by Nishisonic** [ElectronicObserverEN/ElectronicObserver#226] opened 2022-08-11 11:58 UTC
普段であれば艦船図鑑/装備図鑑はすぐ開くが、長時間起動している状態で艦船図鑑/装備図鑑を開くと74式がフリーズする
数分位放置するとフリーズが解除されるが、この状態の時は艦これの通信も行えなくなる

Windwos 11 Pro
ver. 5.1.9.0 - 2022/07/03 Release
.NET 6.0.6

![image](https://user-images.githubusercontent.com/12210425/184126581-45651dd6-1033-4c99-8216-31a69f747be1.png)

**Comment by myangelkamikaze** [comment] 2022-08-14 04:57
I tried to reproduce the freeze, but it always opened normally.

I first tried opening it when you reported, at that point my 74式 was running for a few days. Then I restarted 74式 before going to sleep and tried again after waking up, which was about 7~8 hours. In both cases it opened instantly.

Does this happen every time or just once, and then it works normally? Does it happen only the first time when you open it, or also if you opened it before?

From code, I can't find anything that could cause problems. On an older CPU, a slight delay is possible, but that would be a few seconds at worst. I/O shouldn't be problematic either because the ship image gets loaded asynchronously.

Actually, I/O could cause a problem when restoring window state. On startup `Settings\WindowStates\[ElectronicObserver.Window.Tools.DialogAlbumMasterShip.DialogAlbumMasterShipWpf]DialogAlbumMasterShipView.json` gets loaded, but that probably shouldn't be taking long either.

**Comment by Nishisonic** [comment] 2022-08-17 16:52
Thanks for the reply.
In order to solve this problem, I restarted my PC and deleted a set of 74 files
and downloaded it again, and it no longer occurs.
I don't know if it is because I originally installed andante's ElectronicObserver by overwriting it, or if it is because my PC has been running for a long time (about 25 days), but since it no longer occurs, you can close it.
Thank you.

**Comment by myangelkamikaze** [comment] 2022-08-18 03:14
I can't imagine any of those being a problem. But I have no idea what could cause it, and since we can't really investigate it, I'll close this issue.

**Closed by myangelkamikaze** 2022-08-18 03:14 UTC
Labels: bug
