### ISSUE TITLE
Game stucks when enemy air raids against land bases in 6-5

### ISSUE THREAD

**Issue by blackpepperlolz** [ElectronicObserverEN/ElectronicObserver#386] opened 2023-08-27 13:56 UTC
As title describe, Game stuck when enemy air raids against land bases in 6-5, shown as below figure.
Game screen stop no matter how long I wait.
Not the internet issue, Game run normally when I try to use other browser. 

![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/35715350/05f018a6-6ca4-463b-a0aa-6cf7156815a6)

my observer version is 5.2.9

Thank you

**Comment by myangelkamikaze** [comment] 2023-08-27 14:48
Is there any error in the log?
It might be a cache issue.

**Comment by blackpepperlolz** [comment] 2023-08-27 14:50
No sir,
No error in the log.

**Comment by myangelkamikaze** [comment] 2023-08-27 14:56
Open devtools. In the network tab, disable cache. Try another run and see if it gets stuck. Note that devtools have to stay open. This is similar to clearing the cache, but it won't actually be totally cleared.
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/316f1ceb-40f2-48cc-afb3-aeecd58d7e52)
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/10831df2-dec4-446c-867e-94ed7fe54f19)

**Comment by Heinrike** [comment] 2023-08-30 03:42
I had the same issue caused by a bad kcs2\resources\map\006\05_info.json in my cache. In OP's screenshot, the air base is not displayed, so when an air raid spawns, the game becomes locked because it doesn't know where to play the air raid animation.

This should be fixed if you delete the bad file from your cache and redownload it from the game servers.

**Comment by myangelkamikaze** [comment] 2023-08-30 04:09
Note that the files saved by 七四式 never get read, so those files don't serve as a cache, they're basically logging.
The missing AB marker is a good point, I didn't notice that. So yeah, it's certainly a cache issue and the solution I gave should solve it.
Thanks for the confirmation.

**Closed by myangelkamikaze** 2023-08-30 04:09 UTC
