### ISSUE TITLE
ログイン時パスワードの入力設定が無効になり、勝手にログインされてしまう。

### ISSUE THREAD

**Issue by riteman1** [ElectronicObserverEN/ElectronicObserver#356] opened 2023-04-27 05:02 UTC
再現手順は不明なのですが、2回同じ症状が発生しまたので報告します。

ログイン時、パスワードを入力する設定にしているにも関わらず、ゲーム中に「更新」・「キャッシュを削除」・「キャッシュを無視して更新」のどれかを特定の順番で行うと、ログイン時にパスワード入力画面をスキップしてゲームが開始されるようになってしまいます。
パスワードを変更すると、ログイン時にパスワード入力画面になるので、このアプリに原因があるものと思われます。

**Comment by myangelkamikaze** [comment] 2023-04-27 06:27
So, if I understand correctly, you have your DMM login set up like this? And you'd expect to have to log in again when you refresh?
![image](https://user-images.githubusercontent.com/40002167/234776843-04d80bd1-dc52-4f02-8536-f6c4f43ad94a.png)

From testing, it seems like if you uncheck 「次回から自動でログインする」 you'll need to log in again after restarting 七四式 itself, refresh will keep you logged in. This is probably the correct way of working, refreshing the website shouldn't cancel your session.

In general, we're not doing anything on the DMM page, so the behavior should be the same as with normal browsers such as Firefox, Edge etc.

**Comment by riteman1** [comment] 2023-04-27 09:29
No, my login screen settings are below.

![image](https://user-images.githubusercontent.com/121211716/234821081-255a44c6-08bc-45f6-be03-9d6b1de43cc6.png)

**Comment by myangelkamikaze** [comment] 2023-04-27 11:07
Yes, as explained under the image, refresh should not log you out in this case, only closing 七四式  should log you out.

**Comment by riteman1** [comment] 2023-04-27 13:51
No.
Even if 七十四式 is closed, I start 七十四式 and log in without enter password, so I peport this action.

**Comment by myangelkamikaze** [comment] 2023-04-28 02:35
I tested this multiple times with both CefSharp and WebView2 and couldn't reproduce the problem.
Are you using the latest version?
Can you make a video showing the wrong behavior?

**Comment by riteman1** [comment] 2023-04-28 10:42
Yes.
It occurred in the latest version of 七四式, and it has also occurred in the previous version.
After changing the password again, 七四式 returned to the login screen.
I also checked the checkbox and it was in the same state as my report.
I'll let you know when I figure out how to reproduce it.

**Comment by myangelkamikaze** [comment] 2023-11-17 03:44
I don't think there's anything we can do here.

**Closed by myangelkamikaze** 2023-11-17 03:44 UTC
